### ISSUE TITLE
doesn't work with latest nvidia driver on Ubuntu

### ISSUE THREAD

**Issue by wrf3** [Syllo/nvtop#55] opened 2020-01-09 22:55 UTC
apt-get install nvtop

The following NEW packages will be installed:
  libnvidia-compute-418 libnvidia-compute-430 ...

The following packages will be REMOVED:
  libnvidia-compute-435 ...

Can nvtop be updated to use the current driver?  Thanks.

**Comment by georgebisbas** [comment] 2020-02-12 01:26
Hi wrf3,
Have you tried building it?
https://github.com/Syllo/nvtop#nvtop-build
It worked for me.

**Comment by Syllo** [comment] 2020-02-19 11:07
This is related to the explanation in issue #51, where the Ubuntu team added a dependency that forbids the installation for more recent versions.

Duplicate of #51

**Closed by Syllo** 2020-02-19 11:07 UTC
