### ISSUE TITLE
Problems with nvtop on dual GPU (Intel+Nvidia)

### ISSUE THREAD

**Issue by ibobak** [Syllo/nvtop#207] opened 2023-04-28 08:40 UTC
I have MSI Titan GT77 HX 13VI  laptop with two video cards: 

```
/$ lspci | grep -i vga
0000:00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-S UHD Graphics (rev 04)
0000:01:00.0 VGA compatible controller: NVIDIA Corporation GN21-X11 [GeForce RTX 4090 Laptop GPU] (rev a1)
```

I am getting this message when running nvtop:

```
This version of Nvtop is missing support for reporting Intel GPU memory, power, fan and temperature
<Don't Show Again> <Ok>

Press Enter to select, arrows ">" and "<" to switch optionsnvtop: ./src/extract_gpuinfo_intel.c:228: parse_drm_fdinfo_intel: 
Assertion `!cache_entry_check && "We should not be processing a client id twice per update"' failed.
```

I want to mention that after reboot nvtop works fine for some time (even after the message that it won't work for intel card). 
But in 1 or 2 hours of work it stops working, and when launching it again I am getting a message as above.

May I ask you a question:  is is possible to somehow unplug monitoring the Intel GPU and to start monitoring ONLY the Nvidia GPU?  Is there some option?  Or maybe I can unplug this in the source code somehow and make a custom build for myself? If yes, would you be so kind as to tell how?

I truly don't need to look at intel card:  I am interesting to monitor only my nvidia card.
Thanks in advance.

**Comment by Ashvith10** [comment] 2023-05-13 22:24
Duplicate of #197 

Have you tried this?
```
sudo setcap cap_perfmon=+ep /usr/bin/nvtop
```

Also make sure that you have `intel_gpu_top` installed and set the same for this utility as well.
```
sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
```

**Comment by Syllo** [comment] 2023-05-21 11:45
You can select which GPU is monitored through the F2 menu too.

**Comment by Syllo** [comment] 2023-05-21 11:46
The Intel limitation comes from the driver not providing some metrics yet.

**Comment by Syllo** [comment] 2023-06-11 09:22
I'll close this for now. Missing info related to #197
Feel free to re-open if you feel like I am missing something.

**Closed by Syllo** 2023-06-11 09:22 UTC
