### ISSUE TITLE
installing on Ubuntu causes uninstallation of driver

### ISSUE THREAD

**Issue by Goddard** [Syllo/nvtop#112] opened 2021-07-04 12:49 UTC
I think because of dependencies, or something I am unsure, but installing on Ubuntu caused my Nvidia driver to be uninstalled.  This is ubuntu 21.04.

**Comment by Syllo** [comment] 2021-07-24 15:17
Duplicate of #51

I just updated the package for a release on Debian.

Once the Debian nvidia maintainer pushes the package to debian testing, Ubuntu should pull the update, which will fix the dependency issue.

**Closed by Syllo** 2021-07-24 15:17 UTC
