### ISSUE TITLE
Dependend on general user-specific environment variables: Takes `tabs -8` for granted

### ISSUE THREAD

**Issue by fbruetting** [Syllo/nvtop#192] opened 2023-02-20 20:38 UTC
`v3.0.1`

I have `tabs -4` in my `.bashrc`, as I all my code uses a tab width of 4, and thus want my CLI dev tools to reflect that. `nvtop` however strongly depends on the user setting `tabs -8` (or the user not modifying `tabs` command), because otherwise it produces distorted graphs. See the following images. The mentioned commands should make them reproducible.

Summary: It would be good if `nvtop` would not depend on general user settings and produce correct graphs, no matter what the user `tabs` width setting is.

## `tabs -8; nvtop`

![Bildschirmfoto vom 2023-02-20 21-26-48](https://user-images.githubusercontent.com/10520767/220193947-6101319c-8c4d-40c9-9f44-3b07aa49e616.png)

## `tabs -4; nvtop`

![Bildschirmfoto vom 2023-02-20 21-27-47](https://user-images.githubusercontent.com/10520767/220193985-099bcfc9-eff1-4b31-b64c-468eaf64eefc.png)

**Comment by Syllo** [comment] 2023-04-12 10:18
Weird, I cannot reproduce it on my system within gnome-terminal. On top of that, the graph plot does not use tabs at all so I am a bit confused.

Which terminal emulator and system are you using?

**Comment by Syllo** [comment] 2023-05-21 11:49
Closing and follow issue #200

**Closed by Syllo** 2023-05-21 11:49 UTC
